### ISSUE TITLE
Missing `misc` module

### ISSUE THREAD

**Issue by Behery** [rosewang2008/gym-cooking#1]
Hi,
This looks great, I can't wait to try it! 
However, when I tried to run as described in the documentation, I get an error about a missing module `misc`. 
```python
(gym) $ python main.py --num-agents 4 --level partial-divider_salad --model1 greedy --model2 bd --model3 fb --model4 dc
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from misc.game.gameplay import GamePlay
ModuleNotFoundError: No module named 'misc'
```
am I missing something? or doing something wrong here?
thanks!

**Comment by rosewang2008** [comment]
Hi @Behery! Are you using python3? Make sure when you run `python --version` it outputs something >= python 3.6.

**Comment by Behery** [comment]
thanks for the quick reply, I'm using Python 3.7.9

**Comment by rosewang2008** [comment]
Ah you're totally right - I forgot to push the misc directory. Do you mind running it now? Thanks for letting me know!

**Comment by Behery** [comment]
Great! now it's running. Thanks :) :)
