### ISSUE TITLE
Unable to run example command: ModuleNotFoundError

### ISSUE THREAD

**Issue by hhjoel** [rosewang2008/gym-cooking#4]
Hello,

I've forked and clone your repo and tried to run the command `python main.py --num-agents 2 --level partial-divider_salad --model1 bd --model2 bd` but am not able to run it successfully:

![image](https://user-images.githubusercontent.com/44512838/103947665-6f942200-5173-11eb-866c-75edde39b3e7.png)

Will it be possible for you to help?

Thank you.

**Comment by hhjoel** [comment]
Perhaps I should also mention that I'm not able to install torch==1.6.0 (`pip install torch==1.6.0`) with this error:

ERROR: Could not find a version that satisfies the requirement torch==1.6.0
ERROR: No matching distribution found for torch==1.6.0

I'm only able to `pip install torch` (version 1.7.1)

**Comment by rosewang2008** [comment]
Hi Joel, It seems like it's not able to find the Overcooked gym environment. Could you try pip install it like in the instructions? 

Let me know if that resolves the issue! 

<img width="659" alt="Screen Shot 2021-01-07 at 1 40 06 PM" src="https://user-images.githubusercontent.com/26608062/103947990-db33ac00-50ed-11eb-90c6-47b3c3707070.png">

**Comment by hhjoel** [comment]
Hi Rose,

Thanks for your prompt response!

Actually, I followed the instructions and did `pip3 install -e .`

To be safe, I re-ran the command and got this:

![image](https://user-images.githubusercontent.com/44512838/103993032-ee1ead00-51cf-11eb-8c3d-8c0e11daf252.png)

Since I couldn't install torch==1.6.0, I installed torch==1.7.1. Could that be the problem?

Thanks!

**Comment by rosewang2008** [comment]
I noticed that I accidentally included torch in the `requirements.txt` and `setup.py` files -- you shouldn't actually need it and I've updated those files accordingly. Could you try pulling and installing again?

**Comment by hhjoel** [comment]
Yes, I managed to install and run it now, thanks a lot! Closing the issue now!
