### ISSUE TITLE
Two variables with the same name mixup

### ISSUE THREAD

**Issue by Eirin3** [rosewang2008/gym-cooking#6]
Hi Rose,

Great project! I really enjoyed the images visualizing each step.

However, I ran into the following error when trying to run experiments with the --with-image-obs and --record commands:
![Capture](https://user-images.githubusercontent.com/56752549/110496207-8dd7b900-80f5-11eb-8276-4f254722dfe7.PNG)

I believe the issue lies in the following part of the overcooked_environment.py file, where the new_obs variable is used for two different objects - the OvercookedEnvironment and a GameImage:
![Capturee](https://user-images.githubusercontent.com/56752549/110496514-d5f6db80-80f5-11eb-8a44-5fcbb7c14f31.PNG)

When I renamed the new_obs variables on lines 210 and 213, everything worked fine.

**Comment by rosewang2008** [comment]
Hi @Eirin3!
Thanks for bringing this to my attention. I recently updated the repo with [this commit](https://github.com/rosewang2008/gym-cooking/commit/bed2ba50d8f1adf4ae78ebd01ca5595788f3c1ad).

Basically the changes are: 
* `new_obs` is also the planning-based representation object.
* by default, `info['image_obs']` will always give you the image of the updated environment state.
